# Generated by Django 5.1.6 on 2025-03-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="address",
            new_name="address1",
        ),
        migrations.AddField(
            model_name="customer",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
