# Generated by Django 5.1.6 on 2025-03-04 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_address_customer_address1_customer_address2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="company_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="note",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="郵便番号はXXX-XXXXの形式で入力してください。",
                        regex="^\\d{3}-\\d{4}$",
                    )
                ],
            ),
        ),
    ]
