# Generated by Django 5.1.6 on 2025-03-04 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_name_customer_company_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
    ]
